#
# Component Makefile
#
COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/include
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/api
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/debugger
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/ecma/base
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/ecma/builtin-objects
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/ecma/builtin-objects/typedarray
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/ecma/operations
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/jcontext
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/jmem
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/jrt
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/lit
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/parser/js
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/parser/regexp
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/profiles
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-core/vm
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-ext/arg
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-ext/handler
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-ext/include
COMPONENT_ADD_INCLUDEDIRS += jerryscript/jerry-ext/module

COMPONENT_SRCDIRS += jerryscript/jerry-core
COMPONENT_SRCDIRS += jerryscript/jerry-core/api
COMPONENT_SRCDIRS += jerryscript/jerry-core/debugger
COMPONENT_SRCDIRS += jerryscript/jerry-core/ecma/base
COMPONENT_SRCDIRS += jerryscript/jerry-core/ecma/builtin-objects
COMPONENT_SRCDIRS += jerryscript/jerry-core/ecma/builtin-objects/typedarray
COMPONENT_SRCDIRS += jerryscript/jerry-core/ecma/operations
COMPONENT_SRCDIRS += jerryscript/jerry-core/jcontext
COMPONENT_SRCDIRS += jerryscript/jerry-core/jmem
COMPONENT_SRCDIRS += jerryscript/jerry-core/jrt
COMPONENT_SRCDIRS += jerryscript/jerry-core/lit
COMPONENT_SRCDIRS += jerryscript/jerry-core/parser/js
COMPONENT_SRCDIRS += jerryscript/jerry-core/parser/regexp
COMPONENT_SRCDIRS += jerryscript/jerry-core/profiles
COMPONENT_SRCDIRS += jerryscript/jerry-core/vm
COMPONENT_SRCDIRS += jerryscript/jerry-ext/arg
COMPONENT_SRCDIRS += jerryscript/jerry-ext/handler
COMPONENT_SRCDIRS += jerryscript/jerry-ext/module
